package com.example.gsontestingground.json;

/**
 * Generated by the test GsonTest.createStringsIdClass()
 * Author: Nemanja Trajkovic
 */
public class StringsId {

public static final String hello = "hello";
public static final String welcome = "welcome";
public static final String previousButton = "previousButton";
public static final String nextButton = "nextButton";
public static final String selectLanguage = "selectLanguage";
public static final String description = "description";

}